/**
 * Machine-readable error codes returned by the API.
 * The frontend maps each code to a translated message via the `errors` namespace in i18n.
 * The error `message` is still included in API responses (in Spanish, the source language)
 * for backward compatibility and as a fallback when the client cannot map a code.
 */
export const ERROR_CODES = {
  ERR_PASSWORD_REQUIRED: 'ERR_PASSWORD_REQUIRED',
  ERR_INCORRECT_PASSWORD: 'ERR_INCORRECT_PASSWORD',
  ERR_TOKEN_NOT_PROVIDED: 'ERR_TOKEN_NOT_PROVIDED',
  ERR_INVALID_TOKEN_FORMAT: 'ERR_INVALID_TOKEN_FORMAT',
  ERR_INVALID_OR_EXPIRED_TOKEN: 'ERR_INVALID_OR_EXPIRED_TOKEN',
  ERR_COMMAND_REQUIRED: 'ERR_COMMAND_REQUIRED',
  ERR_INVALID_ACTION: 'ERR_INVALID_ACTION',
  ERR_SERVER_ALREADY_RUNNING: 'ERR_SERVER_ALREADY_RUNNING',
  ERR_START_SCRIPT_NOT_FOUND: 'ERR_START_SCRIPT_NOT_FOUND',
  ERR_BINARY_NOT_FOUND: 'ERR_BINARY_NOT_FOUND',
  ERR_SERVER_ALREADY_STOPPED: 'ERR_SERVER_ALREADY_STOPPED',
  ERR_STOP_WHILE_UPDATING: 'ERR_STOP_WHILE_UPDATING',
  ERR_NO_ACTIVE_PROCESS: 'ERR_NO_ACTIVE_PROCESS',
  ERR_SERVER_NOT_ACTIVE_FOR_COMMANDS: 'ERR_SERVER_NOT_ACTIVE_FOR_COMMANDS',
  ERR_UPDATE_WHILE_RUNNING: 'ERR_UPDATE_WHILE_RUNNING',
  ERR_STEAMCMD_NOT_FOUND: 'ERR_STEAMCMD_NOT_FOUND',
  ERR_STEAMCMD_BRANCH_DISCOVERY_FAILED: 'ERR_STEAMCMD_BRANCH_DISCOVERY_FAILED',
  ERR_STEAMCMD_BRANCH_DISCOVERY_TIMEOUT: 'ERR_STEAMCMD_BRANCH_DISCOVERY_TIMEOUT',
  ERR_STEAMCMD_BRANCH_DISCOVERY_EMPTY: 'ERR_STEAMCMD_BRANCH_DISCOVERY_EMPTY',
  ERR_VDF_PARSE_FAILED: 'ERR_VDF_PARSE_FAILED',
  ERR_UPDATE_FAILED: 'ERR_UPDATE_FAILED',
  ERR_CRITICAL_RESTORE_FAILED: 'ERR_CRITICAL_RESTORE_FAILED',
  ERR_INVALID_FILE_TYPE: 'ERR_INVALID_FILE_TYPE',
  ERR_PATH_TRAVERSAL_DETECTED: 'ERR_PATH_TRAVERSAL_DETECTED',
  ERR_READ_FILE_FAILED: 'ERR_READ_FILE_FAILED',
  ERR_SAVE_FILE_FAILED: 'ERR_SAVE_FILE_FAILED',
  ERR_CONTENT_NOT_PROVIDED: 'ERR_CONTENT_NOT_PROVIDED',
  ERR_DATA_NOT_PROVIDED: 'ERR_DATA_NOT_PROVIDED',
  ERR_UNSUPPORTED_GUI_TYPE: 'ERR_UNSUPPORTED_GUI_TYPE',
  ERR_UNSUPPORTED_SERIALIZE_TYPE: 'ERR_UNSUPPORTED_SERIALIZE_TYPE',
  ERR_INSTANCE_NAME_REQUIRED: 'ERR_INSTANCE_NAME_REQUIRED',
  ERR_INSTANCE_BRANCH_REQUIRED: 'ERR_INSTANCE_BRANCH_REQUIRED',
  ERR_INSTANCE_NAME_TAKEN: 'ERR_INSTANCE_NAME_TAKEN',
  ERR_INSTANCE_NOT_FOUND: 'ERR_INSTANCE_NOT_FOUND',
  ERR_INSTANCE_NAME_INVALID: 'ERR_INSTANCE_NAME_INVALID',
  ERR_INSTANCE_PORTS_INVALID: 'ERR_INSTANCE_PORTS_INVALID',
  ERR_INSTANCE_HAS_RUNNING_PROCESS: 'ERR_INSTANCE_HAS_RUNNING_PROCESS',
  ERR_INSTANCE_ALREADY_EXISTS: 'ERR_INSTANCE_ALREADY_EXISTS',
  ERR_INSTANCE_CANNOT_MIGRATE_TO_SELF: 'ERR_INSTANCE_CANNOT_MIGRATE_TO_SELF',
  ERR_INSTANCE_CREATE_FAILED: 'ERR_INSTANCE_CREATE_FAILED',
  ERR_INSTANCE_DELETE_FAILED: 'ERR_INSTANCE_DELETE_FAILED',
  ERR_INSTANCE_MIGRATE_FAILED: 'ERR_INSTANCE_MIGRATE_FAILED',
  ERR_INSTANCE_DATA_DIR_NOT_FOUND: 'ERR_INSTANCE_DATA_DIR_NOT_FOUND',
  ERR_BACKUP_NOT_FOUND: 'ERR_BACKUP_NOT_FOUND',
  ERR_BACKUP_RESTORE_RUNNING: 'ERR_BACKUP_RESTORE_RUNNING',
  ERR_BACKUP_CREATE_FAILED: 'ERR_BACKUP_CREATE_FAILED',
  ERR_BACKUP_RESTORE_FAILED: 'ERR_BACKUP_RESTORE_FAILED',
  ERR_BACKUP_DELETE_FAILED: 'ERR_BACKUP_DELETE_FAILED'
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
