/**
 * Global User-facing and log Strings for the Project Zomboid Server Portal backend.
 */
export const SERVER_STRINGS = {
  ERR_PASSWORD_REQUIRED: 'Contraseña requerida',
  ERR_INCORRECT_PASSWORD: 'Contraseña incorrecta',
  ERR_TOKEN_NOT_PROVIDED: 'Token no provisto.',
  ERR_INVALID_TOKEN_FORMAT: 'Formato de token inválido.',
  ERR_INVALID_OR_EXPIRED_TOKEN: 'Token inválido o expirado.',
  ERR_COMMAND_REQUIRED: 'Comando requerido',
  ERR_INVALID_ACTION: 'Acción inválida',
  ERR_SERVER_ALREADY_RUNNING: 'El servidor ya está en ejecución, iniciándose o actualizándose.',
  ERR_START_SCRIPT_NOT_FOUND: 'No se encontró el script de inicio en {path}. Asegúrate de actualizar/instalar el juego primero.',
  ERR_BINARY_NOT_FOUND: 'No se encontró el ejecutable principal en {path}.',
  ERR_SERVER_ALREADY_STOPPED: 'El servidor ya está detenido.',
  ERR_STOP_WHILE_UPDATING: 'No se puede detener mientras se actualiza.',
  ERR_NO_ACTIVE_PROCESS: 'No se detectó ningún proceso activo de Project Zomboid.',
  ERR_SERVER_NOT_ACTIVE_FOR_COMMANDS: 'El servidor no está activo para recibir comandos.',
  ERR_UPDATE_WHILE_RUNNING: 'No se puede actualizar mientras el servidor está en ejecución o actualizándose.',
  ERR_STEAMCMD_NOT_FOUND: 'No se encontró SteamCMD en: {path}. Por favor reinicia el contenedor.',
  ERR_UPDATE_FAILED: 'ERROR: La descarga o validación falló (Código: {code}).',
  ERR_CRITICAL_RESTORE_FAILED: 'Error crítico al restaurar la versión anterior: {message}',
  ERR_INVALID_FILE_TYPE: 'Tipo de archivo inválido.',
  ERR_PATH_TRAVERSAL_DETECTED: 'Intento de Path Traversal bloqueado.',
  ERR_READ_FILE_FAILED: 'Error al leer archivo {type}: {message}',
  ERR_SAVE_FILE_FAILED: 'Error al guardar archivo {type}: {message}',
  
  MSG_STARTING_SERVER: '[Manager] Iniciando el servidor de Project Zomboid...',
  MSG_SERVER_ONLINE: '[Manager] El servidor de Project Zomboid está en línea y listo para recibir conexiones.',
  MSG_SERVER_EXIT: '[Manager] El proceso del juego finalizó. Código: {code}, Señal: {signal}',
  MSG_STOPPING_SERVER: '[Manager] Solicitando detención segura del servidor (guardando partida)...',
  MSG_FORCE_STOPPING_SERVER: '[Manager] El servidor no se detuvo a tiempo. Forzando cierre (SIGKILL)...',
  MSG_FORCE_STOP_SIGKILL: '[Manager] Deteniendo servidor de forma forzosa (SIGKILL)...',
  MSG_SIGKILL_JAVA: '[Manager] Enviando SIGKILL al PID de Java real: {pid}',
  MSG_SIGKILL_SPAWN: '[Manager] Enviando SIGKILL al proceso principal de spawn: {pid}',
  MSG_STARTING_UPDATE: '[Manager] Iniciando proceso de actualización vía SteamCMD...',
  MSG_BRANCH_CHANGE_DETECTED: '[Manager] Detectado cambio de rama (instalada: "{installed}", solicitada: "{requested}"). Preparando cambio seguro...',
  MSG_STEAMCMD_DOWNLOADING: '[SteamCMD] Ejecutando descarga del AppID 380870 {branch}...',
  MSG_STEAMCMD_EXIT: '[SteamCMD] Proceso finalizado. Código de salida: {code}',
  MSG_UPDATE_SUCCESS: '[Manager] Actualización completada con éxito. Rama registrada: "{branch}"',
  MSG_CLEANING_BACKUP: '[Manager] Eliminando archivos de la versión anterior para liberar espacio...',
  MSG_RESTORING_VERSION: '[Manager] Restaurando versión anterior desde el backup...',
  MSG_RESTORE_COMPLETE: '[Manager] Restauración completada. El servidor se mantiene en la versión anterior.',
  MSG_NO_BACKUP_TO_RESTORE: '[Manager] No hay versión anterior para restaurar.',
  MSG_INACTIVITY_SHUTDOWN_UPDATED: '[Manager] Configuración de auto-apagado por inactividad actualizada a: {minutes} minutos.',
  MSG_PLAYER_COUNT_UPDATED: '[Manager] Conteo de jugadores conectados actualizado: {count}',
  MSG_SERVER_EMPTY_SHUTDOWN: '[Manager] El servidor está vacío. Programando apagado automático en {minutes} minutos.',
  MSG_CANCELING_SHUTDOWN_TIMER: '[Manager] Se detectaron jugadores conectados ({count}) o el auto-apagado fue desactivado. Cancelando temporizador.',
  MSG_TRIGGERING_INACTIVITY_SHUTDOWN: '[Manager] Ejecutando apagado automático por inactividad (0 jugadores conectados durante {minutes} minutos).',
  MSG_JSON_CONFIG_MISSING: '[Manager] Archivo ProjectZomboid64.json no encontrado en: {path}. Se omitió la configuración.',
  MSG_JVM_CONFIGURED: '[Manager] Ajustes configurados: Min={min}GB, Max={max}GB, Idioma={lang}',
  MSG_PORTAL_RUNNING: '[PZ Web Portal] Corriendo bajo Clean Architecture en http://{host}:{port}',

  // Express route messages
  ERR_CONTENT_NOT_PROVIDED: 'Contenido no provisto',
  ERR_DATA_NOT_PROVIDED: 'Datos no provistos',
  ERR_UNSUPPORTED_GUI_TYPE: 'Tipo de archivo no soportado para análisis GUI',
  ERR_UNSUPPORTED_SERIALIZE_TYPE: 'Tipo de archivo no soportado para serialización GUI'
};
