/**
 * Global User-facing and log Strings for the Project Zomboid Server Portal backend.
 */
export const SERVER_STRINGS = {
  ERR_PASSWORD_REQUIRED: 'Contraseña requerida',
  ERR_INCORRECT_PASSWORD: 'Contraseña incorrecta',
  ERR_TOKEN_NOT_PROVIDED: 'Token no provisto.',
  ERR_INVALID_TOKEN_FORMAT: 'Formato de token inválido.',
  ERR_INVALID_OR_EXPIRED_TOKEN: 'Token inválido o expirado.',
  ERR_COMMAND_REQUIRED: 'Comando requerido',
  ERR_INVALID_ACTION: 'Acción inválida',
  ERR_SERVER_ALREADY_RUNNING: 'El servidor ya está en ejecución, iniciándose o actualizándose.',
  ERR_START_SCRIPT_NOT_FOUND: 'No se encontró el script de inicio en {path}. Asegúrate de actualizar/instalar el juego primero.',
  ERR_BINARY_NOT_FOUND: 'No se encontró el ejecutable principal en {path}.',
  ERR_SERVER_ALREADY_STOPPED: 'El servidor ya está detenido.',
  ERR_STOP_WHILE_UPDATING: 'No se puede detener mientras se actualiza.',
  ERR_NO_ACTIVE_PROCESS: 'No se detectó ningún proceso activo de Project Zomboid.',
  ERR_SERVER_NOT_ACTIVE_FOR_COMMANDS: 'El servidor no está activo para recibir comandos.',
  ERR_UPDATE_WHILE_RUNNING: 'No se puede actualizar mientras el servidor está en ejecución o actualizándose.',
  ERR_STEAMCMD_NOT_FOUND: 'No se encontró SteamCMD en: {path}. Por favor reinicia el contenedor.',
  ERR_STEAMCMD_BRANCH_DISCOVERY_FAILED: 'No se pudo obtener la lista de ramas de Steam (SteamCMD). Motivo: {message}',
  ERR_STEAMCMD_BRANCH_DISCOVERY_TIMEOUT: 'SteamCMD no respondió al consultar las ramas disponibles antes de {seconds} segundos.',
  ERR_STEAMCMD_BRANCH_DISCOVERY_EMPTY: 'SteamCMD devolvió una respuesta sin ramas publicables para el AppID {appId}.',
  ERR_VDF_PARSE_FAILED: 'No se pudo interpretar la respuesta VDF de SteamCMD: {message}',
  ERR_UPDATE_FAILED: 'ERROR: La descarga o validación falló (Código: {code}).',
  ERR_CRITICAL_RESTORE_FAILED: 'Error crítico al restaurar la versión anterior: {message}',
  ERR_INVALID_FILE_TYPE: 'Tipo de archivo inválido.',
  ERR_PATH_TRAVERSAL_DETECTED: 'Intento de Path Traversal bloqueado.',
  ERR_READ_FILE_FAILED: 'Error al leer archivo {type}: {message}',
  ERR_SAVE_FILE_FAILED: 'Error al guardar archivo {type}: {message}',
  
  MSG_STARTING_SERVER: '[Manager] Iniciando el servidor de Project Zomboid...',
  MSG_SERVER_ONLINE: '[Manager] El servidor de Project Zomboid está en línea y listo para recibir conexiones.',
  MSG_SERVER_EXIT: '[Manager] El proceso del juego finalizó. Código: {code}, Señal: {signal}',
  MSG_STOPPING_SERVER: '[Manager] Solicitando detención segura del servidor (guardando partida)...',
  MSG_FORCE_STOPPING_SERVER: '[Manager] El servidor no se detuvo a tiempo. Forzando cierre (SIGKILL)...',
  MSG_FORCE_STOP_SIGKILL: '[Manager] Deteniendo servidor de forma forzosa (SIGKILL)...',
  MSG_SIGKILL_JAVA: '[Manager] Enviando SIGKILL al PID de Java real: {pid}',
  MSG_SIGKILL_SPAWN: '[Manager] Enviando SIGKILL al proceso principal de spawn: {pid}',
  MSG_STARTING_UPDATE: '[Manager] Iniciando proceso de actualización vía SteamCMD...',
  MSG_BRANCH_CHANGE_DETECTED: '[Manager] Detectado cambio de rama (instalada: "{installed}", solicitada: "{requested}"). Preparando cambio seguro...',
  MSG_STEAMCMD_DOWNLOADING: '[SteamCMD] Ejecutando descarga del AppID 380870 {branch}...',
  MSG_STEAMCMD_EXIT: '[SteamCMD] Proceso finalizado. Código de salida: {code}',
  MSG_BRANCHES_DISCOVERY_STARTED: '[Manager] Consultando ramas disponibles del AppID {appId} vía SteamCMD...',
  MSG_BRANCHES_DISCOVERY_STDOUT: '[Manager] SteamCMD devolvió {bytes} bytes de información del AppID.',
  MSG_BRANCHES_FALLBACK_USED: '[Manager] SteamCMD no devolvió ramas válidas ({message}). Se usará la lista de respaldo configurada.',
  MSG_UPDATE_SUCCESS: '[Manager] Actualización completada con éxito. Rama registrada: "{branch}"',
  MSG_CLEANING_BACKUP: '[Manager] Eliminando archivos de la versión anterior para liberar espacio...',
  MSG_RESTORING_VERSION: '[Manager] Restaurando versión anterior desde el backup...',
  MSG_RESTORE_COMPLETE: '[Manager] Restauración completada. El servidor se mantiene en la versión anterior.',
  MSG_NO_BACKUP_TO_RESTORE: '[Manager] No hay versión anterior para restaurar.',
  MSG_INACTIVITY_SHUTDOWN_UPDATED: '[Manager] Configuración de auto-apagado por inactividad actualizada a: {minutes} minutos.',
  MSG_PLAYER_COUNT_UPDATED: '[Manager] Conteo de jugadores conectados actualizado: {count}',
  MSG_SERVER_EMPTY_SHUTDOWN: '[Manager] El servidor está vacío. Programando apagado automático en {minutes} minutos.',
  MSG_CANCELING_SHUTDOWN_TIMER: '[Manager] Se detectaron jugadores conectados ({count}) o el auto-apagado fue desactivado. Cancelando temporizador.',
  MSG_TRIGGERING_INACTIVITY_SHUTDOWN: '[Manager] Ejecutando apagado automático por inactividad (0 jugadores conectados durante {minutes} minutos).',
  MSG_JSON_CONFIG_MISSING: '[Manager] Archivo ProjectZomboid64.json no encontrado en: {path}. Se omitió la configuración.',
  MSG_JVM_CONFIGURED: '[Manager] Ajustes configurados: Min={min}GB, Max={max}GB, Idioma={lang}',
  MSG_PORTAL_RUNNING: '[PZ Web Portal] Corriendo bajo Clean Architecture en http://{host}:{port}',

  // Express route messages
  MSG_ACTION_START: 'Servidor iniciándose...',
  MSG_ACTION_STOP: 'Deteniendo servidor de forma segura...',
  MSG_ACTION_RESTART: 'Reiniciando el servidor de forma segura...',
  MSG_ACTION_KILL: 'Servidor detenido forzosamente.',
  MSG_ACTION_UPDATE: 'Iniciando actualización del servidor...',
  MSG_ACTION_COMMAND: 'Comando enviado con éxito.',
  ERR_CONTENT_NOT_PROVIDED: 'Contenido no provisto',
  ERR_DATA_NOT_PROVIDED: 'Datos no provistos',
  ERR_UNSUPPORTED_GUI_TYPE: 'Tipo de archivo no soportado para análisis GUI',
  ERR_UNSUPPORTED_SERIALIZE_TYPE: 'Tipo de archivo no soportado para serialización GUI',

  // Instance management
  ERR_INSTANCE_NAME_REQUIRED: 'El nombre de la instancia es obligatorio',
  ERR_INSTANCE_BRANCH_REQUIRED: 'La rama de Steam es obligatoria',
  ERR_INSTANCE_NAME_TAKEN: 'Ya existe una instancia con el nombre "{name}"',
  ERR_INSTANCE_NOT_FOUND: 'No se encontró la instancia con id {id}',
  ERR_INSTANCE_NAME_INVALID: 'El nombre de la instancia solo puede contener letras, números, guiones y guiones bajos (3-32 caracteres)',
  ERR_INSTANCE_PORTS_INVALID: 'Los puertos deben estar entre 1024 y 65535 y no pueden coincidir',
  ERR_INSTANCE_HAS_RUNNING_PROCESS: 'Detén la instancia antes de eliminarla o migrar sus datos',
  ERR_INSTANCE_ALREADY_EXISTS: 'Ya existe una instancia en esa ubicación',
  ERR_INSTANCE_CANNOT_MIGRATE_TO_SELF: 'La instancia origen y destino no pueden ser la misma',
  ERR_INSTANCE_CREATE_FAILED: 'No se pudo crear la instancia: {message}',
  ERR_INSTANCE_DELETE_FAILED: 'No se pudo eliminar la instancia: {message}',
  ERR_INSTANCE_MIGRATE_FAILED: 'No se pudo migrar la instancia: {message}',
  ERR_INSTANCE_DATA_DIR_NOT_FOUND: 'La instancia origen no tiene directorio de datos para migrar',

  // Backup management
  ERR_BACKUP_NOT_FOUND: 'No se encontró el respaldo "{id}"',
  ERR_BACKUP_RESTORE_RUNNING: 'Detén la instancia antes de restaurar un respaldo para evitar corrupción de datos',
  ERR_BACKUP_CREATE_FAILED: 'No se pudo crear el respaldo: {message}',
  ERR_BACKUP_RESTORE_FAILED: 'No se pudo restaurar el respaldo: {message}',
  ERR_BACKUP_DELETE_FAILED: 'No se pudo eliminar el respaldo: {message}',

  MSG_INSTANCE_CREATED: '[Manager] Instancia "{name}" creada correctamente',
  MSG_INSTANCE_DELETED: '[Manager] Instancia "{name}" eliminada',
  MSG_INSTANCE_SELECTED: '[Manager] Instancia activa: "{name}"',
  MSG_INSTANCE_MIGRATED: '[Manager] Datos de usuario migrados de "{source}" a "{target}"',
  MSG_INSTANCE_UPDATED: '[Manager] Instancia "{name}" descargada/actualizada (rama: {branch})',
  MSG_FAST_REUSE_COPY: '[Instalación Rápida] Reusando archivos descargados de la rama "{branch}" desde "{source}"...',
  MSG_CANCELING_INSTALLATION: '[Manager] Cancelando instalación/descarga activa para la instancia "{name}"...',
  MSG_BACKUP_CREATED: '[Backup] Respaldo "{name}" creado para el servidor "{instance}"',
  MSG_BACKUP_RESTORED: '[Backup] Respaldo "{name}" restaurado con éxito en el servidor "{instance}"',
  MSG_BACKUP_DELETED: '[Backup] Respaldo "{name}" eliminado'
};
